### ISSUE TITLE
Peer Review - Documentation Issues

### ISSUE THREAD

**Issue by erik-whiting** [onnela-lab/beiwe-backend#210]
Some issues from my review of the documentation. Review is being coordinated [here](https://github.com/openjournals/joss-reviews/issues/3417)

**_Installation Instructions_** - There are several issues with the development setup:
  * The line in step one `sudo apt-get install postgresql python-psycopg2 libpq-dev` breaks because `python-psycopg2` is a package you can install with pip. The package is in your `requirements.txt` file, so you don't need special instructions to install it.
  * The last line of your suggested `private/environment.sh` file has the sysadmin email as "sysadmin@localhst" is this a typo or is that the correct email address?
  * Installing the requirements from `requirements.txt` failed with message `error: launchpadlib 1.10.13 requires testresources`. I ran `pip3 install testresources` which fixed the error but you should include that package in `requirements.txt` since it isn't a standard library module
  * Under "Local Celery setup" the link provided in step 1 is broken and goes to a 404 page. I had to install rabbit mq manually
  * The line `sudo rabbitmqctl set_permissions -p / beiwe ".*" ".*" ".*"` failed because there's no such user "beiwe." Am I supposed to use my own user or was there a step I missed / step that wasn't documented?
  * Running celery after this line doesn't work because the connection is refused. I'm guessing it has something to do with the above issue
  * Step 7 doesn't work either, I assume because of the two issues above, but it's also throwing database errors. I see that there is a Django app in this repo, are there some Django setup steps missing from the README?
  * There is a wiki for running locally located here: https://github.com/onnela-lab/beiwe-backend/wiki/How-to-Run-Beiwe-Locally, but it is outdated compared to when the README was last updated, so I'm not sure which directions to follow

**_Example Usage_** - The checklist item for this says "Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)" I do not see such examples. Is this solely the backend for the Beiwe mobile app? i.e., are there not really any examples to show here? If so, I guess no examples are needed.

**_Some Concerns_** - Not listed on the checklist but I have a concern. In the README, you say this system is built with Python 3.6. Python 3.6 end-of-life is December 23rd, 2021. That's about six months from now. If you were to add a little more test coverage, you could set up a build server like CircleCI for free and run the test suite with multiple Python versions pretty easily and be able to deal with EOLs confidently. If this is something you're interested in pursuing and would like help with, I don't mind pointing you in the right direction or helping out a bit. If you _**do**_ have CI/CD set up already, it is not obvious, but I apologize for missing it if I did.

I cannot review the areas in the Functionality portion of the checklist until the installation issues are fixed or a workaround is suggested

**Comment by biblicabeebli** [comment]
Hello! I've been following your posts, this is very interesting and quite helpful!  You've caught me (us, really, though I don't want to speak for others) at an odd moment.  I would love to get in contact, and be a little more active in responding and commenting as soon as time and commitments allow.

Would greatly appreciate it if you could send me an email so we could get in touch, I've set up biblicabeiwe at gmail dot com.  (let me know if that isn't working.)

**Comment by erik-whiting** [comment]
@biblicabeebli send you an email, check your spam folder. I'm erik at erikwhiting dot com

**Comment by biblicabeebli** [comment]
- The line in step one sudo apt-get install postgresql python-psycopg2 libpq-dev breaks because python-psycopg2 is a package you can install with pip. The package is in your requirements.txt file, so you don't need special instructions to install it.

I've addressed this documentation on the branch `peer-review`.  there's more to get through so no pull request yet.  I believe the origin of this detail was related to virtual environments (or a lack thereof), so I added a statement about virtual environments beforehand.

**Comment by biblicabeebli** [comment]
- The last line of your suggested private/environment.sh file has the sysadmin email as "sysadmin@localhst" is this a typo or is that the correct email address?

lol, typo. pushed on `peer-review`

**Comment by biblicabeebli** [comment]
- Installing the requirements from requirements.txt failed with message error: launchpadlib 1.10.13 requires testresources. I ran pip3 install testresources which fixed the error but you should include that package in requirements.txt since it isn't a standard library module

I don't know what you encountered here, launchpadlib is not a dependency of any library in use right now*, and I don't think it was at the time.  More relevantly, pip should have installed that on the first go?  Maybe you were running an older version of pip and some bug resulted in a missing dependency?  I don't know what's going on here, and I can't replicate.

That said, I will go ahead and add a `pip install --upgrade pip setuptools wheel` to the instructions to avoid pip-related issues.

**Comment by biblicabeebli** [comment]
- Under "Local Celery setup" the link provided in step 1 is broken and goes to a 404 page. I had to install rabbit mq manually

fixed on peer-review

**Comment by erik-whiting** [comment]
> * Installing the requirements from requirements.txt failed with message error: launchpadlib 1.10.13 requires testresources. I ran pip3 install testresources which fixed the error but you should include that package in requirements.txt since it isn't a standard library module
> 
> I don't know what you encountered here, launchpadlib is not a dependency of any library in use right now, and I don't think it was at the time. More relevantly, pip should have installed that on the first go? Maybe you were running an older version of pip and some bug resulted in a missing dependency? I don't know what's going on here, and I can't replicate.
> 
> That said, I will go ahead and add a `pip install --upgrade pip setuptools wheel` to the instructions to avoid pip-related issues.
> 
> edit: had a random * hanging out in the text...

@biblicabeebli the line you added still throws an error for me. I was able to get around it by running `sudo apt install python3-testresources`. I'm not really sure what was causing the error and maybe it's something on my side only (I am blowing away everything before running the setup tasks to simulate a brand-new contributor with a brand-new machine trying to get started with this repo).

I defer to you if you want to add that line to your setup script or not since I'm not sure if it's a me-specific problem; if you choose to leave it out of the setup script I'll still mark this part of the issue as fixed.

**Comment by biblicabeebli** [comment]
- Under "Local Celery setup" the link provided in step 1 is broken and goes to a 404 page. I had to install rabbit mq manually
- The line sudo rabbitmqctl set_permissions -p / beiwe ".*" ".*" ".*" failed because there's no such user "beiwe." Am I supposed to use my own user or was there a step I missed / step that wasn't documented?
- Running celery after this line doesn't work because the connection is refused. I'm guessing it has something to do with the above issue

I've gone and updated this section considerably.  `rabbitmq` is such a pain to work with that I ended up writing ~dirty~ clever a hack that bypasses it entirely for local testing purposes.  We only bother with Celery+rabbitmq on the data processing servers now, which have automated deployment and configuration.  Directions are as good and complete as I can make them, last I checked Ubuntu 20.04+ was magically incompatible with those directions, and I've noted that.

**Comment by biblicabeebli** [comment]
> @biblicabeebli the line you added still throws an error for me. I was able to get around it by running `sudo apt install python3-testresources`. I'm not really sure what was causing the error and maybe it's something on my side only (I am blowing away everything before running the setup tasks to simulate a brand-new contributor with a brand-new machine trying to get started with this repo).

Hunh.  Um.  Are you using a virtual environment, or the system environment?

**Comment by erik-whiting** [comment]
> > @biblicabeebli the line you added still throws an error for me. I was able to get around it by running `sudo apt install python3-testresources`. I'm not really sure what was causing the error and maybe it's something on my side only (I am blowing away everything before running the setup tasks to simulate a brand-new contributor with a brand-new machine trying to get started with this repo).
> 
> Hunh. Um. Are you using a virtual environment, or the system environment?

virtual

**Comment by biblicabeebli** [comment]
python3-testresources is another pip install masquerading as a system install for the system python environment.  Maybe it is installing some other, related system dependency that you are missing? buh?

I'm using this to get legible output from apt, and I've followed a couple dependencies, it doesn't really go that deep... python3, six, python3 packaging junk...
`apt show python3-testresources| grep ^Depends`

I guess our instructions don't actually state the other more common system dependencies, we only declare the third-party binaries that you may be missing and wouldn't just-incidentally-know without interrogating the python requirements file and already knowing voodoo facts about python. (Like "oh yeah, psycopg2 is the postgres library because that's totally obvious... oh and it has a compilation step as part of a python install... unless you declare it as 'psycopg2-binary'...")

I wouldn't and didn't think to include things like gcc (really any compiler) as a required dependency, that just seemed to basic.  This isn't a line of thought I've reflected on much.  I have no problem adding a couple extra items like python3 and gcc to the apt installs, it costs us nothing and could help someone out eventually, I'm just not sure where that line is.... but I do know that it is not this obscure testing library.

Could you post the command and output that is stating it is missing this plus the output of pip list?

**Comment by biblicabeebli** [comment]
- can't reproduce
hooray! or... whatever.  Problem "solved"

- gcc
okay

- virtual -> venv
no miscommunication there

**Comment by biblicabeebli** [comment]
https://github.com/onnela-lab/beiwe-backend/wiki/Tips-For-Local-Beiwe-Development

- There is a wiki for running locally located here: https://github.com/onnela-lab/beiwe-backend/wiki/How-to-Run-Beiwe-Locally, but it is outdated compared to when the README was last updated, so I'm not sure which directions to follow

Yup, that was confusing.  I've updated the name to more accurately reflect what the page is for, and I'm adding that link to the readme.

new link [https://github.com/onnela-lab/beiwe-backend/wiki/Tips-For-Local-Beiwe-Development](https://github.com/onnela-lab/beiwe-backend/wiki/Tips-For-Local-Beiwe-Development)

**Comment by biblicabeebli** [comment]
- Some Concerns - Not listed on the checklist but I have a concern. In the README, you say this system is built with Python 3.6. Python 3.6 end-of-life is December 23rd, 2021. That's about six months from now. If you were to add a little more test coverage, you could set up a build server like CircleCI for free and run the test suite with multiple Python versions pretty easily and be able to deal with EOLs confidently. If this is something you're interested in pursuing and would like help with, I don't mind pointing you in the right direction or helping out a bit. If you do have CI/CD set up already, it is not obvious, but I apologize for missing it if I did.

Yup.  This work got delayed due to personnel (me) issues in moving to be more directly associated with Onnela Lab.  Annoyingly the AWS Python 3.8 environment for Elastic Beanstalk (automated scaling for server deployment) swaps some technology on us, primarily Apache -> nginx.  I maintain the deployment code, but at the moment I'm catching up on bugs, this JOSS review work, and some long-overdue tech issues that need addressing and will ideally be out ~along side the 3.8 (3.7? arg, really need to read up) updates.

Fortunately, I have an experienced colleague who's done this particular major elastic beanstalk version migration, and we already have a substantially more complex one under our belts for the python 2.7-3.6 transition.  Unlike python 2, there are zero code compatibility issues at play.  I've got a local pyenv environment congured on a newer version of python that I can and have swapped to on occasion.

(I even have a branch, `eli/type-annotations-python-37`, that includes a nice type annotation feature (its a __future__ import introduced in 3.7) that allows class functions can declare return type annotations, an otherwise class-static scope, with the type of the class they are contained within.  Super helpful in the IDE.)

**Comment by biblicabeebli** [comment]
-  I see that there is a Django app in this repo, are there some Django setup steps missing from the README?

Among the tech upgrades are swapping out Flask for a full django tech stack.  The reason the code is structured as it is is entirely historical.  This started as a flask-mongo project - what can I say, mistakes were made - and we transitioned from mongo to django+postgres a couple years ago now, but the hack to get flask + django working is... a hack.  The work required to replace all of flask with django frontend is daunting, but I was able to start on that recently and have the work up on the eli/django branch.

Once the Django code is done the amount of overhead required to have a functional test suite will be _substantially_ reduced, and oh-lordy will I be writing a lot of tests.  Then comes a CI.  And probably then a vacation.

**Comment by biblicabeebli** [comment]
- Example Usage - The checklist item for this says "Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)" I do not see such examples. Is this solely the backend for the Beiwe mobile app? i.e., are there not really any examples to show here? If so, I guess no examples are needed.

First - is this the checklist over on https://github.com/openjournals/joss-reviews/issues/3417 ?  I have not _really_ familiarized myself much about JOSS, I need some butt-in-chair time to go through the checklist and work out the questions I / Beiwe needs to ask.

I suspect the answer to your point above is that 1) I'm on the developer side, not the data analysis side, so we may need to pull someone else in, and 2) the locus of the analysis work for Beiwe is currently within the Forest repo, which is here: [https://github.com/onnela-lab/forest](https://github.com/onnela-lab/forest).  Historically there have been other relevant repositories, but they are, as far as I know, totally deprecated.

**Comment by biblicabeebli** [comment]
I believe I have addressed everything in the original post here.  I'm getting notifications on this thread.  Let me know if there is something I have missed.

Potential relevant note: I'm going to be reviewing the (newly copied in) researcher's section of the backend wiki, which is known to be outdated and incorrect.  The tl;dr there is that we lost track of it because it was attached to an old repo.  Literally, we forgot about it.  This is being tracked on issue #226. Further, there are details on that wiki section that are related to data science aspects that I'm simply not an expert in.

**Comment by erik-whiting** [comment]
@biblicabeebli nothing needed, you can close this if you like
